language: r
latex: false
pandoc: false
warnings_are_errors: true

r_packages:
  - roxygen2
  - nloptr

addons:
  apt:
    packages:
    - libgit2-dev
  homebrew:
    packages:
    - libgit2

stages:
- name: test
  if: tag IS blank
- name: coverage
  if: tag IS blank
- name: deploy
  if: tag IS present

jobs:
  include:
  - r: release
    os: linux
    cache: packages
  - r: devel
    os: linux
    cache: packages
  - r: 3.6
    os: linux
    cache: packages
  - r: release
    os: osx
    osx_image: xcode12.2
    cache:
      - directories: 
        - externalobjects
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Cellar
        - /usr/local/gfortran
        - $HOME/R
  - stage: coverage
    r: release
    os: linux
    r_packages:
    - covr
    script:
    - travis_wait 30 Rscript -e 'covr::codecov(type=c("tests","examples"))'
    cache: packages
  - stage: deploy
    r: release
    os: osx
    osx_image: xcode12.2
    cache:
      - directories: 
        - externalobjects
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Cellar
        - /usr/local/gfortran
        - $HOME/R
    script:
    - make binary
    deploy:
      provider: releases
      token:
        secure: V0UAes1YbF80zUnOhV8W3fgL16R3s6Dp28LxHT/Z07HaZruI1SnuNrxLRCLG54sY+7WKrZUz7d8hAYMQmDNDWmctAffBgomy4lKsXhi6OiytFbWi+8np616syzqB0kfF14wysqF8dldGFXd4ArHIx4JGmsPiAbiWx3mBaYtrqmG6rhCpD6+tM+EttK4n8eg6c1Mq0rnbmJd+0ZlSYz+55ueTsGv1zF14oScI/+C1ghHgwAghzhvFtTimTCU7dkLxFoZtTD1WEHDdqwsqwfr++vyM7GkTi/gvxxIMgB0fH1NkgRt+VMutODv49qX1E5PoLE7KoQI9zy0ij20n+O0waGVvM6fTlaxf+qb+UnCs7hypwFFGLb3eMJgmcptWEs048KjHcnEv8etMeYYF+ljkQ4euMoDoBMPE+7yLFRyWihI0gsBBRfvOFeab1PnSXuMCojxfwMz+gsdOt5wfgWR2fycQ5hpDMS58W+UgGML7FbQyd8smw8xIyBFSxfO9APgrNoLG86atmPv27pDPoEw2q7D98OPHZXt/j7lrA59TyEOi4DpozoyW37RKhqLkOEjxJOz+NM2u9duIMdNgOuq2qfuAiJRFqhEKvA5dArZadJEzUlzjGUUWKlmiTHeAkiJE0+3tuS5PgkC1VuuxYE42TYFfQHalf2gJsU4VfCj4Ji8=
      file_glob: true
      file:
      - ouch_*.tgz
      skip_cleanup: true
      on:
        tags: true
